name: run-test

on:
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: chmod +x
        if: runner.os == 'Linux'
        run: chmod +x generate_stat.sh
      - name: run script
        run: python main.py
      - name: check generated files (Linux)
        if: runner.os == 'Linux'
        run: ls
      - name: check generated files (Windows)
        if: runner.os == 'Windows'
        run: dir
